# Generated by Django 6.0.1 on 2026-01-31 02:18

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('governorate', models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('giza', 'Giza'), ('alexandria', 'Alexandria'), ('dakahlia', 'Dakahlia'), ('red_sea', 'Red Sea'), ('beheira', 'Beheira'), ('fayoum', 'Fayoum'), ('gharbiya', 'Gharbiya'), ('ismailia', 'Ismailia'), ('menofia', 'Menofia'), ('minya', 'Minya'), ('qaliubiya', 'Qaliubiya'), ('new_valley', 'New Valley'), ('suez', 'Suez'), ('aswan', 'Aswan'), ('assiut', 'Assiut'), ('beni_suef', 'Beni Suef'), ('port_said', 'Port Said'), ('damietta', 'Damietta'), ('sharkia', 'Sharkia'), ('south_sinai', 'South Sinai'), ('kafr_el_sheikh', 'Kafr El-Sheikh'), ('matrouh', 'Matrouh'), ('luxor', 'Luxor'), ('qena', 'Qena'), ('north_sinai', 'North Sinai'), ('sohag', 'Sohag')], max_length=50, null=True)),
                ('grade', models.CharField(blank=True, choices=[('1', 'الصف الأول الثانوي'), ('2', 'الصف الثاني الثانوي'), ('3', 'الصف الثالث الثانوي')], max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
